//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class active_threads
    {
        public int a_id { get; set; }
        public string topic { get; set; }
        public int t_id { get; set; }
    
        public virtual thread thread { get; set; }
    }
}
