//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class feedback
    {
        public int f_id { get; set; }
        public int u_id { get; set; }
        public string sentIP { get; set; }
        public string content { get; set; }
        public System.DateTime time_sent { get; set; }
        public int admin_id { get; set; }
        public Nullable<int> reply_id { get; set; }
        public int read { get; set; }
    
        public virtual user user { get; set; }
    }
}
