//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class journal
    {
        public int j_id { get; set; }
        public string post { get; set; }
        public System.DateTime created { get; set; }
    }
}
