//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pm
    {
        public int pm_id { get; set; }
        public int sent_u_id { get; set; }
        public int recieve_u_id { get; set; }
        public System.DateTime time_sent { get; set; }
        public string content { get; set; }
        public int read { get; set; }
    }
}
