//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class post
    {
        public int p_id { get; set; }
        public int t_id { get; set; }
        public int u_id { get; set; }
        public string thread { get; set; }
        public string post1 { get; set; }
        public int approve { get; set; }
        public int disapprove { get; set; }
        public System.DateTime created { get; set; }
    }
}
