//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int u_id { get; set; }
        public string regIP { get; set; }
        public string loginIP { get; set; }
        public string pseudonym { get; set; }
        public string password { get; set; }
        public int userlvl { get; set; }
        public int posts { get; set; }
        public bool agree { get; set; }
    }
}
